# Generated by Django 5.2.5 on 2025-09-13 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieID', models.IntegerField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=30)),
                ('Actor1Name', models.CharField(max_length=30)),
                ('Actor2Name', models.CharField(max_length=30)),
                ('DirectorName', models.CharField(max_length=30)),
                ('MovieGenre', models.CharField(max_length=30)),
                ('ReleaseYear', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2035)])),
            ],
        ),
    ]
